[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app --workers=2 --threads=2"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
PYTHON_VERSION = "3.10.11"